name: vps

on:
  workflow_dispatch:  # manual trigger
  schedule:           # optional cron to auto-run
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  build:
    runs-on: self-hosted  # <-- change this from ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run VPS
        run: curl -sSf https://sshx.io/get | sh -s run
